development:
  image_host: ''
  host: 'http://localhost:3000'
  # katalk_app_id: '8f99f22318da1458ef402be08af6db0a'
production:
  image_host: 'http://vaskit.kr'
  host: 'http://vaskit.kr'
  # katalk_app_id: '8f99f22318da1458ef402be08af6db0a'
